# Generated by Django 2.2 on 2019-06-02 04:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('philhealth', models.CharField(max_length=20)),
                ('highest_education', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(blank=True, max_length=20)),
                ('file_upload', models.FileField(upload_to='resident/%Y/%m/%d/')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
