# Generated by Django 2.2 on 2019-06-02 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190602_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgyresident',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
